---
apiVersion: batch/v1
kind: Job
metadata:
  name: petclinic-schema
  labels:
    app: psql-init-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: pgsql12-client
          image: quay.io/rhdevelopers/openshift-pgsql12-primary:centos7-clients
          imagePullPolicy: Always
          env:
            - name: PGHOST
              value: postgresql
            - name: PGDATABASE
              value: mydb
            - name: PGUSER
              value: developer
            - name: PGPASSWORD
              value: developer

          command: ["/usr/pgsql-12/bin/psql"]
          volumeMounts:
            - name: init-dump
              mountPath: /tmp/import.sql
              subPath: import.sql
          args: ["--dbname=mydb", "--no-password", "--file=/tmp/import.sql"]
      restartPolicy: Never
      volumes:
        - name: init-dump
          configMap:
            name: postgres-init-dump
  backoffLimit: 1
