name: Build and Deploy

on:
  push:
    branches: [master]

env:
  REGISTRY: quay.io
  REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  OPENSHIFT_NAMESPACE: nithinkuruba-dev

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          version: "4.6"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Maven Package
        run: |
          ./mvnw package -DskipTests -Dquarkus.container-image.push=true

      - name: Restart Petclinic App
        run: |
          oc rollout restart deployment/quarkus-petclinic -n ${{ env.OPENSHIFT_NAMESPACE }}
